/** Matches #cboCountyId in frmEstateSearch2.aspx (value, label). */
export const MD_COUNTIES: { value: string; label: string }[] = [
  { value: "1", label: "Allegany" },
  { value: "2", label: "Anne Arundel" },
  { value: "3", label: "Baltimore" },
  { value: "24", label: "Baltimore City" },
  { value: "4", label: "Calvert" },
  { value: "5", label: "Caroline" },
  { value: "6", label: "Carroll" },
  { value: "7", label: "Cecil" },
  { value: "8", label: "Charles" },
  { value: "9", label: "Dorchester" },
  { value: "10", label: "Frederick" },
  { value: "11", label: "Garrett" },
  { value: "12", label: "Harford" },
  { value: "13", label: "Howard" },
  { value: "14", label: "Kent" },
  { value: "15", label: "Montgomery" },
  { value: "16", label: "Prince George's" },
  { value: "17", label: "Queen Anne's" },
  { value: "19", label: "Somerset" },
  { value: "18", label: "St. Mary's" },
  { value: "20", label: "Talbot" },
  { value: "21", label: "Washington" },
  { value: "22", label: "Wicomico" },
  { value: "23", label: "Worcester" },
];
